from __future__ import annotations

from pathlib import Path

from modeltripwire.models.schemas import ExperimentSummary


def write_markdown_report(summary: ExperimentSummary, path: str | Path) -> Path:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    category_lines = "\n".join(
        f"- **{category}**: {metrics}" for category, metrics in summary.category_breakdown.items()
    )
    scenario_lines = "\n".join(
        f"- **{scenario}**: {metrics}" for scenario, metrics in summary.scenario_breakdown.items()
    )
    benchmark_lines = "\n".join(
        f"- **{benchmark}**: {metrics}" for benchmark, metrics in summary.benchmark_breakdown.items()
    )
    tripwire_lines = "\n".join(
        f"- **{name}**: {count}" for name, count in summary.tripwire_summary.items()
    ) or "- No tripwires triggered"
    failure_lines = "\n".join(
        f"- {failure['prompt_id']} ({failure['scenario']} / {failure['category']}), tripwires={failure['tripwire_count']}, severity={failure['max_severity']}"
        for failure in summary.notable_failures
    ) or "- No notable failures"
    aggregate_confidence = summary.aggregate_metrics.get("mean_score_confidence")
    limitations = "\n".join(f"- {item}" for item in summary.limitations)
    next_steps = "\n".join(f"- {item}" for item in summary.next_steps)

    content = f"""# {summary.title}

## Experiment overview

This report summarizes a structured adversarial evaluation run generated by ModelTripwire.

## Evaluated models

- {', '.join(summary.model_names)}

## Run metadata

- Run ID: {summary.run_id or 'n/a'}
- Run label: {summary.run_label or 'n/a'}
- Benchmark suite: {summary.benchmark_suite or 'mixed/unspecified'}

## Methodology

Prompt cases were run through the configured provider, then scored with rule-based heuristics and, when enabled, blended with judge-assisted scoring. Results were evaluated against configured tripwires, persisted, and summarized for analysis.

## Research question

{summary.research_question}

## Prompt categories

{category_lines}

## Aggregate results

- Total cases: {summary.total_cases}
- Aggregate metrics: {summary.aggregate_metrics}
- Mean score confidence: {aggregate_confidence if aggregate_confidence is not None else 'n/a'}

## Tripwire summary

{tripwire_lines}

## Category breakdown

{category_lines}

## Scenario breakdown

{scenario_lines}

## Benchmark breakdown

{benchmark_lines}

## Notable failures

{failure_lines}

## Limitations

{limitations}

## Next steps

{next_steps}
"""
    output_path.write_text(content, encoding="utf-8")
    return output_path
