from __future__ import annotations

from pathlib import Path

from modeltripwire.models.schemas import ExperimentSummary


def write_markdown_report(summary: ExperimentSummary, path: str | Path) -> Path:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    category_lines = "\n".join(
        f"- **{category}**: {metrics}" for category, metrics in summary.category_breakdown.items()
    )
    tripwire_lines = "\n".join(
        f"- **{name}**: {count}" for name, count in summary.tripwire_summary.items()
    ) or "- No tripwires triggered"
    failure_lines = "\n".join(
        f"- {failure['prompt_id']} ({failure['category']}), tripwires={failure['tripwire_count']}, severity={failure['max_severity']}"
        for failure in summary.notable_failures
    ) or "- No notable failures"
    limitations = "\n".join(f"- {item}" for item in summary.limitations)
    next_steps = "\n".join(f"- {item}" for item in summary.next_steps)

    content = f"""# {summary.title}

## Experiment overview

This report summarizes a structured adversarial evaluation run generated by ModelTripwire.

## Evaluated models

- {', '.join(summary.model_names)}

## Methodology

Prompt cases were run through the configured provider, then scored with rule based heuristics and evaluated against configured tripwires. Results were persisted and summarized for analysis.

## Research question

{summary.research_question}

## Prompt categories

{category_lines}

## Aggregate results

- Total cases: {summary.total_cases}
- Aggregate metrics: {summary.aggregate_metrics}

## Tripwire summary

{tripwire_lines}

## Category breakdown

{category_lines}

## Notable failures

{failure_lines}

## Limitations

{limitations}

## Next steps

{next_steps}
"""
    output_path.write_text(content, encoding="utf-8")
    return output_path
